# Statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alpine
spec:
  serviceName: alpine-service
  replicas: 0
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: localhost:5000/alpine
        ports:
        - containerPort: 5000
