apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  server: podman
  path: /home/ubuntu/apps/mem_intensive/ganesha
  readOnly: "false"
provisioner: nfs
reclaimPolicy: Retain
