# Persistent Volume for redis
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage:  10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: storageclass-nfs
  nfs:
    path: /home/ubuntu/nfs/redis
    server: 10.0.0.180
