# Statefulset for redis
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-service
  replicas: 0
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 10.0.0.180:5000/redis:local
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data/
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-pvc
      imagePullSecrets:
      - name: regcred  
