apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-statefulset
spec:
  replicas: 1
  serviceName: "web-service"
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-container
        image: 10.0.0.180:5000/localweb:local
        command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 1; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
