apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cpu-restore
spec:
  serviceName: cpu-service
  replicas: 1
  selector:
    matchLabels:
      app: cpu-restore
  template:
    metadata:
      labels:
        app: cpu-restore
    spec:
      containers:
      - name: cpu-container
        image: 10.0.0.180:5000/cpu-checkpoint:latest
