apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cpu
spec:
  serviceName: cpu-service
  replicas: 1
  selector:
    matchLabels:
      app: cpu
  template:
    metadata:
      labels:
        app: cpu
    spec:
      containers:
      - name: cpu-container
        image: docker.io/maant001/cpu-intensive:latest
        env:
        - name: NUM_CORES
          value: "3"
        - name: CPU_USAGE_PER_CORE
          value: ""
        # Run the specified script
        command: ["/bin/sh", "-c"]
        args:
        - python3 /cpu_intensive/cpu_state_machine_multicore.py $CPU_USAGE_PER_CORE $NUM_CORES 
        volumeMounts:
        - name: cpulimit-volume
          mountPath: /usr/bin/cpulimit
      volumes:
      - name: cpulimit-volume
        hostPath:
          path: /usr/bin/cpulimit
          type: File
