apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cpu-restore
spec:
  replicas: 1  # Update this value as needed
  selector:
    matchLabels:
      app: cpu-restore
  template:
    metadata:
      labels:
        app: cpu-restore
    spec:
      containers:
      - name: cpu-restore
        image: 10.0.0.180:5000/localcpusinglecorerestore:checkpoint
#  volumeClaimTemplates:
#  - metadata:
#      name: data
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      resources:
#        requests:
#          storage: 1Gi  # Update this value as needed
      nodeName: worker2  # If you still want to specify the node
